#!/bin/bash -l
#BATCH --job-name="ex1"
#SBATCH --account="uzg2"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CRAY_CUDA_MPS=1

array_N=(16 32 48 64 80 96 112 128 144 160)

for j in "${array_N[@]}"
do
	N=$j
	echo $N
        srun srun -n 1 ./openacc $N
done
