#!/bin/bash -l
#SBATCH --job-name="cpi_mpi_jr"
#SBATCH --account="uzh8"
#SBATCH --time=00:05:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun /users/jramzi/HPC_1/exercise_session_03_jramzi/cpi_mpi
